### ISSUE TITLE
Help request: how to do infinite tables

### ISSUE THREAD

**Issue by mike-hogan** [Skayo/svelte-infinite-loading#8]
I have been trying to rework the hacker news example code to use tables, and am failing to get it to work.  Is there any example I can look at, or is infinite scroll not suited to tables?  Thanks,

**Comment by Skayo** [comment]
Could you provide a [Svelte REPL](https://svelte.dev/repl) with your current implementation? Maybe I can try to get it working.

**Comment by mike-hogan** [comment]
Certainly, thanks.  This is a total mess though, sorry

https://svelte.dev/repl/e02305d6ddf341f5ae011d031a11f579?version=3.44.1

**Comment by Skayo** [comment]
Sorry I couldn't respond yesterday, was busy.
Anyways:

Here is your fixed REPL: https://svelte.dev/repl/70aa77f9aff048bebedef20ad68e4eae?version=3.44.2

I think you main problem was using `list.push(...)` instead of having an assignment like `list = [...list, newItem]`. See [here](https://svelte.dev/docs#2_Assignments_are_reactive) for more info.

Then, for some reason, putting the `<InfinteLoading />` component inside a `<tr>` doesn't work. I've changed it to `<div>` and then it actually appeared. Probably an issue that could be solved with CSS - or just use a `<div>`.

Then, always add `let:style {style}` to the element with `slot="item"`. This makes sure the items are rendered correctly.

There are some other improvements, like putting `<tbody>` outside the virtual list, and adding `width: 100%` to the `.tall` class. But these aren't completely essential.

Also, I'm aware that the documentation sucks a bit... But I'm too lazy to make it better and also moved on to some other projects 😅
Sometimes, tho, the documentation of the original Vue.js library might help: [vue-infinite-loading](https://peachscript.github.io/vue-infinite-loading/)

I hope that helps!

**Comment by mike-hogan** [comment]
Wow, this is unbelievable, thanks!  Works like a charm

**Comment by Skayo** [comment]
Happy to help! 😊

**Comment by VsevolodGolovanov** [comment]
Cool component!

I used it with Svelte 5 and a Flowbite Svelte (0.48.6 and 1.0.3) Table. I wanted to leave a link in case someone else comes looking here, but actually my code is quite split up, so I'll add a few links.

[A generic class to handle loading for when you have complete prefetched data.](https://github.com/VsevolodGolovanov/mustapp-exporter/blob/main/src/routes/user/%5Busername%5D/(components)/(tableimpl)/(body)/(infiniteloading)/InfiniteStaticDataLoader.svelte.ts)
[My InfiniteLoading rendering component.](https://github.com/VsevolodGolovanov/mustapp-exporter/blob/main/src/routes/user/%5Busername%5D/(components)/(tableimpl)/(body)/(infiniteloading)/InfiniteRowLoading.svelte)
[Table footer with row counts and a "Show all" button.](https://github.com/VsevolodGolovanov/mustapp-exporter/blob/main/src/routes/user/%5Busername%5D/(components)/(tableimpl)/(footer)/TableInfiniteRowLoadingFooter.svelte)
[Finally, this is my table that uses the 3 things above, bringing everything together.](https://github.com/VsevolodGolovanov/mustapp-exporter/blob/main/src/routes/user/%5Busername%5D/(components)/UserProductListsTable.svelte)

You can it in action [here](https://mustapp-exporter.pages.dev/user/bob).
